config/routes.rb
Rails.application.routes.draw do
  

  root 'posts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get '/home' , to: 'posts#index'
  #get '/home', to: 'static_pages#home'
  get '/newcomments', to: 'static_pages#comments'

  post '/addnewcomment' , to: 'comments#create'
  post '/addnewpost' , to: 'posts#create'
  get '/submit', to: 'static_pages#submit'
  get '/login' , to: 'sessions#new'
  get '/signup' , to: 'users#new'
  get '/about' , to: 'static_pages#about'
  get '/api' , to: 'static_pages#api'
  get '/new' , to: 'users#new'
  get 'login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  
  delete '/logout' , to: 'sessions#destroy'
  match '/signout',  to: 'sessions#destroy', via: :delete
  post "users/:id/posts/:id"    => "comments#create"
  resources :users
  
  
  get '/create' , to: 'posts#create' , via: [:get, :post]
  get '/createcomment' , to: 'comments#new' , via: [:get, :post]
  
  post '/v0/item/create' , to: 'items#create'
  get '/v0/item' , to: 'items#index' , :defaults => { :format => 'json' } 
  get '/v0/item/:id' , to: 'items#show' ,  :defaults => { :format => 'json' } 
  
  resources :users do
  resources :posts
  end
  
  resources :posts, only: [:new, :create, :index] 
  resources :items, only: [:index , :show] , :defaults => { :format => 'json' } 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    
    #define main pages
    def home
        
    end
    
    def comments
    end

    #if user is not logged in redirect to login_path
    def submit
      
        if !logged_in?
            redirect_to login_path
        else
            @post = Post.new
        end
    end
    
    def login
    end
    
    def about
    end
    
    def api
    end


    
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h2><b> Group member 1 name:</h2> <h2>Muhammad AlSharifi</h2>
<h2><b> Group member 1 student number:</h2> <h2>s3607212</h2>
<h2><b> Group member 2 name:</h2> <h2>Zeeshan Mujtaba></h2>
<h2><b>Group member 2 student number:</h2> <h2>s3614080</h2>
<h2><b> heroku deployed URL:</h2>
<h2><a href= "https://obscure-wildwood-77754.herokuapp.com" >Heroku url</a></h2>
<h2><b> assignment 2 bitbucket URL: </b></h2>
<h2><a href= "https://bitbucket.org/s3607212/rad18_assign_2_group_-s3607212-_-s3614080/src/master/" >Bitbucket url</a></h2>

app/views/static_pages/api.html.erb
<% provide(:title, "API") %>

app/views/static_pages/comments.html.erb
<% provide(:title, 'New Comments' ) %>
<div class="container">
    <div class="row">
        <div class="col-md-8">
         <div class="page-header">
            <h1>Comments </h1>
                <div class="comments-list">
                <% get_all_comments.each do |comment| %>    
                    <div class="media">
                      <% postTitle = Post.find_by(id: comment.post_id).title %>   
                      <% username = User.find_by(id: comment.user_id).username %>
                      <% commentBody = comment.content %>
                      <% postId = Post.find_by(id: comment.post_id) %>
                      <% timestamp = time_ago_in_words(comment.created_at) %>
                      <a class="media-left" href="#"></a>
                                
                        <div class="media-body">
                            <b> <%= username %> <%= timestamp %>  on | <%= postTitle %>  </b>
                            <p> <%= commentBody %> </p>
                        </div>
                    </div>           
                 <% end %> 
                </div>
        </div>
</div>
</div>
</div>
                    
                    
                       
                       
                       

<!--
<div id='form'>
<div class="row">
<div class="col-md-12">

<form action="" method="POST" id="commentform">

<div id="comment-name" class="form-row">
<input type = "text" placeholder = "Name (required)" name = "dname"  id = "name" >
</div>
<div id="comment-email" class="form-row">
<input type = "text" placeholder = "Mail (will not be published) (required)" name = "demail"  id = "email">
</div>
<div id="comment-url" class="form-row">
<input type = "text" placeholder = "Website" name = "url"  id = "url" >
</div>
<div id="comment-message" class="form-row">
<textarea name = "comment" placeholder = "Message" id = "comment" ></textarea>
</div>
<a href="#"><input type="submit" name="dsubmit" id="commentSubmit" value="Submit Comment"></a>
<input style="width: 30px" type="checkbox" value="1" name="subscribe" id="subscribe" checked="checked">
<p1><b>Notify me when new comments are added.</b></p1>
</form>

</div>
</div>
</div>
</div>
-->

app/views/static_pages/home.html.erb
<div class="container">
    <div class="row">
    <div class="col-md-8">
     <div class="page-header">
        <h1>Posts </h1>
            </div> 
            <% index = 0 %>
            
               <%= renderPosts(index) %> 
               <%= button_to "More" %>
        
    </div>
    </div>
    </div>
    </div>
 

app/views/static_pages/login.html.erb
 <h1>Rapid application Developmentp</h1>

  <h2>
   Login
  </h2>

  <%= link_to "Sign up now!", '#' , class: "btn btn-lg btn-primary" %>

app/views/static_pages/submit.html.erb
<% provide(:title, 'Submit News' ) %>
<h1>Submit</h1>


<div id='form'>
 <div class="row">
  <div class="col-md-12">
   <%= form_for @post , :url => addnewpost_path  do |f| %>
        <%= render 'shared/post_error_messages' %>
        <%= f.label "Title (required) " %>
        <%= f.text_area :title, class: 'form-control' %>
        <%= f.label "Source (optional)" %>
        <%= f.text_field :source, class: 'form-control' %>
        <%= f.submit "Post" ,  class: "btn btn-primary" %>
      <% end %>  
  </div>
 </div>
</div>