config/routes.rb
Rails.application.routes.draw do
  

  root 'posts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get '/home' , to: 'posts#index'
  #get '/home', to: 'static_pages#home'
  get '/newcomments', to: 'static_pages#comments'

  post '/addnewcomment' , to: 'comments#create'
  post '/addnewpost' , to: 'posts#create'
  get '/submit', to: 'static_pages#submit'
  get '/login' , to: 'sessions#new'
  get '/signup' , to: 'users#new'
  get '/about' , to: 'static_pages#about'
  get '/api' , to: 'static_pages#api'
  get '/new' , to: 'users#new'
  get 'login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  
  delete '/logout' , to: 'sessions#destroy'
  match '/signout',  to: 'sessions#destroy', via: :delete
  post "users/:id/posts/:id"    => "comments#create"
  resources :users
  
  
  get '/create' , to: 'posts#create' , via: [:get, :post]
  get '/createcomment' , to: 'comments#new' , via: [:get, :post]
  
  post '/v0/item/create' , to: 'items#create'
  get '/v0/item' , to: 'items#index' , :defaults => { :format => 'json' } 
  get '/v0/item/:id' , to: 'items#show' ,  :defaults => { :format => 'json' } 
  
  resources :users do
  resources :posts
  end
  
  resources :posts, only: [:new, :create, :index] 
  resources :items, only: [:index , :show] , :defaults => { :format => 'json' } 
end

app/models/post.rb
require 'open-uri'
class Post < ApplicationRecord
  
  has_many :comments
  belongs_to :user
  
  URL_REGEXP = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/
  validates :title , presence: true , length: { minimum: 10 , maximum: 200 , message: " title must be between 10 and 200 charachters long" }
  validates :source , :allow_blank => true , format: { with: URL_REGEXP }

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    #declare constants
    INCREMENT_AMOUNT = 8
    
    #set  before  actions
    before_action :set_page, only: [:index]
     
    #action for showing posts pages
    def show
        post = Post.find_by(id: params[:id])
        #@comment = post.comments
        @newcomment = Comment.new
        @newcomment.post = post
    end
    
    #indexing  of  pagination
    def index
        @posts = Post.order(created_at: :desc).limit(INCREMENT_AMOUNT).offset(@page * INCREMENT_AMOUNT)
    end
   
    #new post
    def new
        before_filter :authenticate_user!
        @post = Post.new
        @user = current_user
    end
    
    #creating post
    def create
        @current_user||= User.find_by(id: session[:user_id])
        @post = @current_user.posts.new(post_params)
        @post.user_id = current_user.id
        #process saving post and display appropiate messages  accordingly
        if @post.save
            flash[:success] = " News posted successfully"
            redirect_to :root
        else
            #redirect back to submit page
            render 'static_pages/submit'
        end
    end
    
    #retrieve all comments 
    def get_all_comments_for_post
        @post = Post.find( params[:id]).comments
    end
    
    private
        #set page  number
        def set_page
            @page = params[:page].to_i || 0
        end
        
        #post params
        def post_params
          params.require(:post).permit(:title, :source)
        end
end

app/helpers/posts_helper.rb
module PostsHelper
    
    COMMENTS_PER_PAGE = 3
    def getAllPosts
        return Post.all
    end
    
    def get_number_of_comments
        Post.find( params[:id]).comments.count
    end
    
    def get_number_of_posts
        return Post.all.count
    end
    
    def get_latest_three_comments
        Post.find( params[:id]).comments.order(created_at: :desc).limit(COMMENTS_PER_PAGE)
       
    end

end

app/views/posts/index.html.erb
<% provide(:title, 'Home Page '+ @page.to_s ) %>
 <div class="page-header">

<ul>
<div class="comments-list">
    <% index = @page * 8 %>  
            <% @posts.each do |post| %>   
            
            <div class="media">
                <% postTitle = post.title %>   
                  <% postSource = post.source %> 
                  <% postOwner = User.find_by(id: post.user_id).username %>
                  <% numOfComments = get_number_of_comments_for(post) %>
                  <% timestamp = time_ago_in_words(post.created_at) %>
                <a class="media-left" href="#">
                </a>
                <div class="media-body">
                    <b> <li> <%= index + 1 %>  
                      <%= postTitle %>  ( <%= link_to postSource , postSource , :target => "_blank" %>  )</b>
                   <p>by <%= postOwner %> <%= timestamp %>  | <%= link_to (get_number_of_comments_for(post).to_s + " comments") , user_post_path( User.find_by(id: post.user_id) , post.id )  %> </p>
                     </li>
                </div>
            </div>   
             <% index += 1 %>  
             
        <% end %> 
        <% page1 = @page %>
        <% page1 += 1 %>
        <% if (index < get_number_of_posts) %>
            <div><%= link_to "More"  , posts_path(page: page1  ) , class: "btn btn-primary form-spacing-top"  %></div>
        <% end %>
</ul>

app/views/posts/show.html.erb
<% provide(:title, Post.find_by(id: params[:id]).title) %>

<h3> <%= Post.find_by(id: params[:id]).title %></h3>
<p> by <%= User.find_by(id: params[:user_id]).username %>  <%= time_ago_in_words(Post.find_by(id: params[:id]).created_at) %> | <%= get_number_of_comments %> comments </p>
    <% if current_user %>
        <%= form_for  @newcomment, :url => addnewcomment_path do |f| %>
          <%= f.hidden_field :post_id %>
          <%= f.text_area :content, class: 'form-control' %>
          <%= f.submit "post comment" , class: "btn btn-primary" %>
        <% end %>
    <% else %>
        <p>  <%= link_to "Login to add Comment", login_path ,   class: "btn btn-primary" %> </p>
    <% end %>
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <div class="page-header">
                Comments
            </div> 
            <div class="comments-list">
            <%  get_latest_three_comments.each do |comment| %>    
                    <div class="media">
                        <b> <%=  comment.user.username %> <%= time_ago_in_words(comment.created_at) %> </b>
                        <p> <%= comment.content %> </p>
                    </div>
            <% end %> 
            </div>
        </div>
    </div>
</div>

          