config/routes.rb
Rails.application.routes.draw do
  

  root 'posts#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  get '/home' , to: 'posts#index'
  #get '/home', to: 'static_pages#home'
  get '/newcomments', to: 'static_pages#comments'

  post '/addnewcomment' , to: 'comments#create'
  post '/addnewpost' , to: 'posts#create'
  get '/submit', to: 'static_pages#submit'
  get '/login' , to: 'sessions#new'
  get '/signup' , to: 'users#new'
  get '/about' , to: 'static_pages#about'
  get '/api' , to: 'static_pages#api'
  get '/new' , to: 'users#new'
  get 'login' , to: 'sessions#new'
  post '/login' , to: 'sessions#create'
  
  delete '/logout' , to: 'sessions#destroy'
  match '/signout',  to: 'sessions#destroy', via: :delete
  post "users/:id/posts/:id"    => "comments#create"
  resources :users
  
  
  get '/create' , to: 'posts#create' , via: [:get, :post]
  get '/createcomment' , to: 'comments#new' , via: [:get, :post]
  
  post '/v0/item/create' , to: 'items#create'
  get '/v0/item' , to: 'items#index' , :defaults => { :format => 'json' } 
  get '/v0/item/:id' , to: 'items#show' ,  :defaults => { :format => 'json' } 
  
  resources :users do
  resources :posts
  end
  
  resources :posts, only: [:new, :create, :index] 
  resources :items, only: [:index , :show] , :defaults => { :format => 'json' } 
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row">
  <div class="col">
   <div class="text-center">
    <%= link_to "API |", 'https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2' %>
    <%= link_to "About",   about_path %>
  </div>
  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar">
  <nav class="navbar navbar-default">
    <div class="container">
        
    <div class="navbar-header">
       <%= link_to image_tag("rmit_white.png", alt: "Brand" ,  :size => '60' ) %>
       <%= link_to "RMIT news", root_path , id: "logo" , :class => "form-spacing-top" %>
   
    </div>
         <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   root_path %></li>
            <li><%= link_to "Comments",   newcomments_path  %></li>
            <li><%= link_to "Submit",   submit_path %></li>
            <% if logged_in? %>
                 <li><%= link_to "Log out", logout_path , method: :delete %></li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
    </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
     <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
  </body>
</html>